service:
  name: serverless-typescript-2
# app and org for use with dashboard.serverless.com
app: serverless-typescript-2
org: slino

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    useChildProcesses: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    ENV_JWT_PRIVATE_KEY: ${param:ENV_JWT_PRIVATE_KEY}
    ENV_MONGO_URI: ${param:ENV_MONGO_URI}

functions:
  mainHandler:
    handler: handler.mainHandler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
